### PR TITLE
Nova v4 Compatibility

### PR DESCRIPTION
**Pull request by LTKort**
Update for Laravel Nova v4 and fix for #118, tested and working on [Laravel Nova](https://nova.laravel.com/) · v4.5.2
Inspired on the initial PR #117

- Using the new Table Rows & Styling from Nova
- Changed to Vue 3 and changed the Draggable package.

Still has an issue with overriding the default fields of Nova:
Nova's bug: Package fails to override Nova's default Vue components
Temporary Fix: https://github.com/laravel/nova-issues/issues/4143#issue-1221940614

Screenshot 2022-05-12 at 15 45 39

### CODE REVIEW

**Comment by LTKort** [comment]
For testing pusoses; Published this fork on [marshmallow/nova-sortable](https://github.com/marshmallow-packages/nova-sortable.git) with v3 tag.
Will remove the package as soon the original is fixed.

**Review by Tarpsvo — APPROVED** [review]

**Comment by goellner** [comment]
The fix on novas side was released today with the 4.6.0 update: https://nova.laravel.com/releases/4.6.0

**Comment by ramcda** [comment]
@LTKort did you do anything special with the install?  Running Nova 4.6.  Installed the package out of dev-main.  Looks like it is not overriding the Nova table rows.  I have the model and resource setup appropriately for sorting.  I'm planning to add some debug code to the ResourceTableRow Vue component and see if i can figure out if it's even attempting to fire.

**Comment by LTKort** [comment]
@ramcda what about v3 instead of main? If it won't work, could you check our fork marshmallow/nova-sortable 

To debug the code you should check https://nova.laravel.com/docs/4.0/customization/frontend.html#vue-devtools

If there are any errors they will be reported in console.

**Comment by ramcda** [comment]
@LTKort Working with v3.0.  Was dealing with a browser side caching issue.  Have a bit more testing to do however the component override in 4.6 is clean now.

**Comment by benedict-w** [comment]
I'm using Nova 4.8 and a ManyToMany sorting as outlined in the documentation. The interface appears to work (when dragging the alert says "Resource Successfully Reordered") but the sort_order in the database does not change. Can anyone confirm whether it should work or not?

**Pull request merged**
